# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 683b96e7bc9ce44fec32b51ef7ce8c2bf9a65413b4dd31d2359635af7922008feb78312b1be8366976fd37e5fe149ab4a9059b207277ac79f3d8a8d64bf7d5cc

test:
  secret_key_base: 4d3e649bc077efa6ddd8642b3adc1bfad162f52c0515400ccd4c5f7ddc84d998ea56e0157883e45ab4e03c98faa67341d8e6f420d67582b3ecef37783edf30ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
